opcodes = {
    # Control: Timing
    "control_wait": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "wait (SECONDS) seconds",
        "inputTypes": {"SECONDS": "positive number"},
        "inputTranslation": {"DURATION": "SECONDS"},
        "optionTypes": {},
    },
    "control_waitsecondsoruntil": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "wait (SECONDS) seconds or until <CONDITION>",
        "inputTypes": {"SECONDS": "positive number", "CONDITION": "boolean"},
        "inputTranslation": {"DURATION": "SECONDS"},
        "optionTypes": {},
    },
    # Control: Loops
    "control_repeat": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "repeat (TIMES) {BODY}",
        "inputTypes": {"TIMES": "number", "BODY": "script"},
        "inputTranslation": {"SUBSTACK": "BODY"},
        "optionTypes": {},
    },
    "control_forever": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "forever {BODY}",
        "inputTypes": {"BODY": "script"},
        "inputTranslation": {"SUBSTACK": "BODY"},
        "optionTypes": {},
    },
    "control_for_each": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "for each [VARIABLE] in (RANGE) {BODY}",
        "inputTypes": {"RANGE": "positive integer", "BODY": "script"},
        "inputTranslation": {"VALUE": "RANGE"},
        "optionTypes": {"VARIABLE": "variable"},
    },
    "control_exitLoop": {
        "type": "lastInstruction",
        "category": "Control",
        "newOpcode": "escape loop",
        "inputTypes": {},
        "optionTypes": {},
    },
    "control_continueLoop": {
        "type": "lastInstruction",
        "category": "Control",
        "newOpcode": "continue loop",
        "inputTypes": {},
        "optionTypes": {},
    },
    # Control: Switches and Cases
    "control_switch": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "switch (CONDITION) {CASES}",
        "inputTypes": {"CONDITION": "round", "CASES": "script"},
        "inputTranslation": {"SUBSTACK": "CASES"},
        "optionTypes": {},
    },
    "control_switch_default": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "switch (CONDITION) {CASES} default {DEFAULT}",
        "inputTypes": {"CONDITION": "round", "CASES": "script", "DEFAULT": "script"},
        "inputTranslation": {"SUBSTACK1": "CASES", "SUBSTACK2": "DEFAULT"},
        "optionTypes": {},
    },
    "control_exitCase": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "exit case",
        "inputTypes": {},
        "optionTypes": {},
    },
    "control_case_next": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "run next case when (CONDITION)",
        "inputTypes": {"CONDITION": "text"},
        "optionTypes": {},
    },
    "control_case": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "case (CONDITION) {BODY}",
        "inputTypes": {"CONDITION": "text", "BODY": "script"},
        "inputTranslation": {"SUBSTACK": "BODY"},
        "optionTypes": {},
    },
    # Control: Conditionals
    "control_if": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "if <CONDITION> then {THEN}",
        "inputTypes": {"CONDITION": "boolean", "THEN": "script"},
        "inputTranslation": {"SUBSTACK": "THEN"},
        "optionTypes": {},
    },
    "control_if_else": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "if <CONDITION> then {THEN} else {ELSE}",
        "inputTypes": {"CONDITION": "boolean", "THEN": "script", "ELSE": "script"},
        "inputTranslation": {"SUBSTACK": "THEN", "SUBSTACK2": "ELSE"},
        "optionTypes": {},
    },
    "control_wait_until": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "wait until <CONDITION>",
        "inputTypes": {"CONDITION": "boolean"},
        "optionTypes": {},
    },
    "control_repeat_until": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "repeat until <CONDITION> {BODY}",
        "inputTypes": {"CONDITION": "boolean", "BODY": "script"},
        "inputTranslation": {"SUBSTACK": "BODY"},
        "optionTypes": {},
    },
    "control_while": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "while <CONDITION> {BODY}",
        "inputTypes": {"CONDITION": "boolean", "BODY": "script"},
        "inputTranslation": {"SUBSTACK": "BODY"},
        "optionTypes": {},
    },
    "control_if_return_else_return": {
        "type": "stringReporter",
        "category": "Control",
        "newOpcode": "if <CONDITION> then (TRUEVALUE) else (FALSEVALUE)",
        "inputTypes": {"CONDITION": "boolean", "TRUEVALUE": "text", "FALSEVALUE": "text"},
        "inputTranslation": {"boolean": "CONDITION", "TEXT1": "TRUEVALUE", "TEXT2": "FALSEVALUE"},
        "optionTypes": {},
    },
    "control_all_at_once": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "all at once {BODY}",
        "inputTypes": {"BODY": "script"},
        "inputTranslation": {"SUBSTACK": "BODY"},
        "optionTypes": {},
    },
    "control_run_as_sprite": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "as ([TARGET]) {BODY}",
        "inputTypes": {"TARGET": "stage || other sprite", "BODY": "script"},
        "inputTranslation": {"SUBSTACK": "BODY"},
        "optionTypes": {},
        "menus": [{"new": "TARGET", "outer": "RUN_AS_OPTION", "inner": "RUN_AS_OPTION", "menuOpcode": "control_run_as_sprite_menu"}],
    },
    # Control: Error Management
    "control_try_catch": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "try to do {TRY} if a block errors {IFERROR}",
        "inputTypes": {"TRY": "script", "IFERROR": "script"},
        "inputTranslation": {"SUBSTACK": "TRY", "SUBSTACK2": "IFERROR"},
        "optionTypes": {},
    },
    "control_throw_error": {
        "type": "lastInstruction",
        "category": "Control",
        "newOpcode": "throw error (ERROR)",
        "inputTypes": {"ERROR": "text"},
        "optionTypes": {},
    },
    "control_error": {
        "type": "stringReporter",
        "category": "Control",
        "newOpcode": "error", # yes that is correct
        "inputTypes": {},
        "optionTypes": {},
    },
    # Control: Extras
    "control_backToGreenFlag": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "run flag", # "run" is not clear enough; so i added "flag"
        "inputTypes": {},
        "optionTypes": {},
    },
    "control_stop_sprite": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "stop sprite ([TARGET])", # changed for uniqueness
        "inputTypes": {"TARGET": "stage || other sprite"},
        "optionTypes": {},
        "menus": [{"new": "TARGET", "outer": "STOP_OPTION", "inner": "STOP_OPTION", "menuOpcode": "control_stop_sprite_menu"}],
    },
    "control_stop": {
        "type": "dynamic", # When "other scripts in sprite" is selected it isn't an ending block
        "category": "Control",
        "newOpcode": "stop script [TARGET]", # changed for uniqueness
        "inputTypes": {},
        "optionTypes": {"TARGET": "stop script target"},
        "optionTranslation": {"STOP_OPTION": "TARGET"},
    },
    # Control: Clones
    "control_start_as_clone": {
        "type": "hat",
        "category": "Control",
        "newOpcode": "when I start as a clone",
        "inputTypes": {},
        "optionTypes": {},
    },
    "control_create_clone_of": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "create clone of ([TARGET])",
        "inputTypes": {"TARGET": "cloning target"},
        "optionTypes": {},
        "menus": [{"new": "TARGET", "outer": "CLONE_OPTION", "inner": "CLONE_OPTION", "menuOpcode": "control_create_clone_of_menu"}],
    },
    "control_delete_clones_of": {
        "type": "instruction",
        "category": "Control",
        "newOpcode": "delete clones of ([TARGET])",
        "inputTypes": {"TARGET": "cloning target"},
        "optionTypes": {},
        "menus": [{"new": "TARGET", "outer": "CLONE_OPTION", "inner": "CLONE_OPTION", "menuOpcode": "control_create_clone_of_menu"}],
    },
    "control_delete_this_clone": {
        "type": "lastInstruction",
        "category": "Control",
        "newOpcode": "delete this clone",
        "inputTypes": {},
        "optionTypes": {},
    },
    "control_is_clone": {
        "type": "booleanReporter",
        "category": "Control",
        "newOpcode": "is clone?",
        "inputTypes": {},
        "optionTypes": {},
    },
}