opcodes = {
    "music_playDrumForBeats": {
        "type": "instruction",
        "category": "Music",
        "newOpcode": "play drum ([DRUM]) for (BEATS) beats",
        "inputTypes": {"DRUM": "drum", "BEATS": "number"},
        "optionTypes": {},
        "menus": [{"new": "DRUM", "outer": "DRUM", "inner": "DRUM", "menuOpcode": "music_menu_DRUM"}],
    },
    "music_restForBeats": {
        "type": "instruction",
        "category": "Music",
        "newOpcode": "rest for (BEATS) beats",
        "inputTypes": {"BEATS": "number"},
        "optionTypes": {},
    },
    "music_playNoteForBeats": {
        "type": "instruction",
        "category": "Music",
        "newOpcode": "play note ([NOTE]) for (BEATS) beats",
        "inputTypes": {"NOTE": "note", "BEATS": "number"},
        "optionTypes": {},
        "menus": [{"new": "NOTE", "outer": "NOTE", "inner": "NOTE", "menuOpcode": "note"}],
    },
    "music_setInstrument": {
        "type": "instruction",
        "category": "Music",
        "newOpcode": "set instrument to ([INSTRUMENT])",
        "inputTypes": {"INSTRUMENT": "instrument"},
        "optionTypes": {},
        "menus": [{"new": "INSTRUMENT", "outer": "INSTRUMENT", "inner": "INSTRUMENT", "menuOpcode": "music_menu_INSTRUMENT"}],
    },
    "music_setTempo": {
        "type": "instruction",
        "category": "Music",
        "newOpcode": "set tempo to (TEMPO)",
        "inputTypes": {"TEMPO": "number"},
        "optionTypes": {},
    },
    "music_changeTempo": {
        "type": "instruction",
        "category": "Music",
        "newOpcode": "change tempo by (TEMPO)",
        "inputTypes": {"TEMPO": "number"},
        "optionTypes": {},
    },
    "music_getTempo": {
        "type": "stringReporter",
        "category": "Music",
        "newOpcode": "tempo",
        "inputTypes": {},
        "optionTypes": {},
        "canHaveMonitor": True,
    },
}