opcodes = {
    "sound_playuntildone": {
        "type": "instruction",
        "category": "Sounds",
        "newOpcode": "play sound ([SOUND]) until done",
        "inputTypes": {"SOUND": "sound"},
        "optionTypes": {},
        "menus": [{"new": "SOUND", "outer": "SOUND_MENU", "inner": "SOUND_MENU", "menuOpcode": "sound_sounds_menu"}],
    },
    "sound_play_at_seconds_until_done": {
        "type": "instruction",
        "category": "Sounds",
        "newOpcode": "play sound ([SOUND]) starting at (SECONDS) seconds until done",
        "inputTypes": {"SOUND": "sound", "SECONDS": "number"},
        "inputTranslation": {"VALUE": "SECONDS"},
        "optionTypes": {},
        "menus": [{"new": "SOUND", "outer": "SOUND_MENU", "inner": "SOUND_MENU", "menuOpcode": "sound_sounds_menu"}],
    },
    "sound_stop": {
        "type": "instruction",
        "category": "Sounds",
        "newOpcode": "stop sound ([SOUND])",
        "inputTypes": {"SOUND": "sound"},
        "optionTypes": {},
        "menus": [{"new": "SOUND", "outer": "SOUND_MENU", "inner": "SOUND_MENU", "menuOpcode": "sound_sounds_menu"}],
    },
    "sound_playallsounds": {
        "type": "instruction",
        "category": "Sounds",
        "newOpcode": "play all sounds",
        "inputTypes": {},
        "optionTypes": {},
    },
    "sound_stopallsounds": {
        "type": "instruction",
        "category": "Sounds",
        "newOpcode": "stop all sounds",
        "inputTypes": {},
        "optionTypes": {},
    },
    "sound_set_stop_fadeout_to": {
        "type": "instruction",
        "category": "Sounds",
        "newOpcode": "set fadeout to (SECONDS) seconds on ([SOUND])",
        "inputTypes": {"SECONDS": "number", "SOUND": "sound"},
        "inputTranslation": {"VALUE": "SECONDS"},
        "optionTypes": {},
        "menus": [{"new": "SOUND", "outer": "SOUND_MENU", "inner": "SOUND_MENU", "menuOpcode": "sound_sounds_menu"}],
    },
    "sound_isSoundPlaying": {
        "type": "booleanReporter",
        "category": "Sounds",
        "newOpcode": "is ([SOUND]) playing?",
        "inputTypes": {"SOUND": "sound"},
        "optionTypes": {},
        "menus": [{"new": "SOUND", "outer": "SOUND_MENU", "inner": "SOUND_MENU", "menuOpcode": "sound_sounds_menu"}],
    },
    "sound_getLength": {
        "type": "stringReporter",
        "category": "Sounds",
        "newOpcode": "length of ([SOUND])?",
        "inputTypes": {"SOUND": "sound"},
        "optionTypes": {},
        "menus": [{"new": "SOUND", "outer": "SOUND_MENU", "inner": "SOUND_MENU", "menuOpcode": "sound_sounds_menu"}],
    },
    "sound_changeeffectby": {
        "type": "instruction",
        "category": "Sounds",
        "newOpcode": "change [EFFECT] sound effect by (AMOUNT)",
        "inputTypes": {"AMOUNT": "number"},
        "inputTranslation": {"VALUE": "AMOUNT"},
        "optionTypes": {"EFFECT": "sound effect"},
    },
    "sound_seteffectto": {
        "type": "instruction",
        "category": "Sounds",
        "newOpcode": "set [EFFECT] sound effect to (VALUE)",
        "inputTypes": {"VALUE": "number"},
        "optionTypes": {"EFFECT": "sound effect"},
    },
    "sound_cleareffects": {
        "type": "instruction",
        "category": "Sounds",
        "newOpcode": "clear sound effects",
        "inputTypes": {},
        "optionTypes": {},
    },
    "sound_getEffectValue": {
        "type": "stringReporter",
        "category": "Sounds",
        "newOpcode": "[EFFECT] sound effect",
        "inputTypes": {},
        "optionTypes": {"EFFECT": "sound effect"},
        "canHaveMonitor": True,
    },
    "sound_changevolumeby": {
        "type": "instruction",
        "category": "Sounds",
        "newOpcode": "change volume by (AMOUNT)",
        "inputTypes": {"AMOUNT": "number"},
        "inputTranslation": {"VOLUME": "AMOUNT"},
        "optionTypes": {},
    },
    "sound_setvolumeto": {
        "type": "instruction",
        "category": "Sounds",
        "newOpcode": "set volume to (VALUE)",
        "inputTypes": {"VALUE": "number"},
        "inputTranslation": {"VOLUME": "VALUE"},
        "optionTypes": {},
    },
    "sound_volume": {
        "type": "stringReporter",
        "category": "Sounds",
        "newOpcode": "volume",
        "inputTypes": {},
        "optionTypes": {},
        "canHaveMonitor": True,
    },
}