opcodes = {
    "Bitwise_isNumberBits": {
        "type": "booleanReporter",
        "category": "Bitwise",
        "newOpcode": "is (NUM) binary?",
        "inputTypes": {"NUM": "number"},
        "inputTranslation": {"CENTRAL": "NUM"},
        "optionTypes": {},
    },
    "Bitwise_toNumberBits": {
        "type": "stringReporter",
        "category": "Bitwise",
        "newOpcode": "(NUM) to binary",
        "inputTypes": {"NUM": "number"},
        "inputTranslation": {"CENTRAL": "NUM"},
        "optionTypes": {},
    },
    "Bitwise_ofNumberBits": {
        "type": "stringReporter",
        "category": "Bitwise",
        "newOpcode": "(NUM) to number",
        "inputTypes": {"NUM": "number"},
        "inputTranslation": {"CENTRAL": "NUM"},
        "optionTypes": {},
    },
    "Bitwise_bitwiseRightShift": {
        "type": "stringReporter",
        "category": "Bitwise",
        "newOpcode": "(NUM) >> (BITS)",
        "inputTypes": {"NUM": "number", "BITS": "number"},
        "inputTranslation": {"LEFT": "NUM", "RIGHT": "BITS"},
        "optionTypes": {},
    },
    "Bitwise_bitwiseLeftShift": {
        "type": "stringReporter",
        "category": "Bitwise",
        "newOpcode": "(NUM) << (BITS)",
        "inputTypes": {"NUM": "number", "BITS": "number"},
        "inputTranslation": {"LEFT": "NUM", "RIGHT": "BITS"},
        "optionTypes": {},
    },
    "Bitwise_bitwiseLogicalRightShift": {
        "type": "stringReporter",
        "category": "Bitwise",
        "newOpcode": "(NUM) >>> (BITS)",
        "inputTypes": {"NUM": "number", "BITS": "number"},
        "inputTranslation": {"LEFT": "NUM", "RIGHT": "BITS"},
        "optionTypes": {},
    },
    "Bitwise_bitwiseCircularRightShift": {
        "type": "stringReporter",
        "category": "Bitwise",
        "newOpcode": "(NUM) >> circular (BITS)",
        "inputTypes": {"NUM": "number", "BITS": "number"},
        "inputTranslation": {"LEFT": "NUM", "RIGHT": "BITS"},
        "optionTypes": {},
    },
    "Bitwise_bitwiseCircularLeftShift": {
        "type": "stringReporter",
        "category": "Bitwise",
        "newOpcode": "(NUM) << circular (BITS)",
        "inputTypes": {"NUM": "number", "BITS": "number"},
        "inputTranslation": {"LEFT": "NUM", "RIGHT": "BITS"},
        "optionTypes": {},
    },
    "Bitwise_bitwiseAnd": {
        "type": "stringReporter",
        "category": "Bitwise",
        "newOpcode": "(OPERAND1) and (OPERAND2)",
        "inputTypes": {"OPERAND1": "number", "OPERAND2": "number"},
        "inputTranslation": {"LEFT": "OPERAND1", "RIGHT": "OPERAND2"},
        "optionTypes": {},
    },
    "Bitwise_bitwiseOr": {
        "type": "stringReporter",
        "category": "Bitwise",
        "newOpcode": "(OPERAND1) or (OPERAND2)",
        "inputTypes": {"OPERAND1": "number", "OPERAND2": "number"},
        "inputTranslation": {"LEFT": "OPERAND1", "RIGHT": "OPERAND2"},
        "optionTypes": {},
    },
    "Bitwise_bitwiseXor": {
        "type": "stringReporter",
        "category": "Bitwise",
        "newOpcode": "(OPERAND1) xor (OPERAND2)",
        "inputTypes": {"OPERAND1": "number", "OPERAND2": "number"},
        "inputTranslation": {"LEFT": "OPERAND1", "RIGHT": "OPERAND2"},
        "optionTypes": {},
    },
    "Bitwise_bitwiseNot": {
        "type": "stringReporter",
        "category": "Bitwise",
        "newOpcode": "not (NUM)",
        "inputTypes": {"NUM": "number"},
        "inputTranslation": {"CENTRAL": "NUM"},
        "optionTypes": {},
    },    
}