opcodes = {
    "data_addtolist": {
        "type": "instruction",
        "category": "Lists",
        "newOpcode": "add (ITEM) to [LIST]",
        "inputTypes": {"ITEM": "text"},
        "optionTypes": {"LIST": "list"},
    },
    "data_deleteoflist": {
        "type": "instruction",
        "category": "Lists",
        "newOpcode": "delete (INDEX) of [LIST]",
        "inputTypes": {"INDEX": "integer"},
        "optionTypes": {"LIST": "list"},
    },
    "data_deletealloflist": {
        "type": "instruction",
        "category": "Lists",
        "newOpcode": "delete all of [LIST]",
        "inputTypes": {},
        "optionTypes": {"LIST": "list"},
    },
    "data_shiftlist": {
        "type": "instruction",
        "category": "Lists",
        "newOpcode": "shift [LIST] by (INDEX)",
        "inputTypes": {"INDEX": "integer"},
        "optionTypes": {"LIST": "list"},
    },
    "data_insertatlist": {
        "type": "instruction",
        "category": "Lists",
        "newOpcode": "insert (ITEM) at (INDEX) of [LIST]",
        "inputTypes": {"ITEM": "text", "INDEX": "integer"},
        "optionTypes": {"LIST": "list"},
    },
    "data_replaceitemoflist": {
        "type": "instruction",
        "category": "Lists",
        "newOpcode": "replace item (INDEX) of [LIST] with (ITEM)",
        "inputTypes": {"INDEX": "integer", "ITEM": "text"},
        "optionTypes": {"LIST": "list"},
    },
    "data_listforeachitem": {
        "type": "instruction",
        "category": "Lists",
        "newOpcode": "For each item [VARIABLE] in [LIST] {BODY}",
        "inputTypes": {"BODY": "script"},
        "inputTranslation": {"SUBSTACK": "BODY"},
        "optionTypes": {"VARIABLE": "variable", "LIST": "list"},
    },
    "data_listforeachnum": {
        "type": "instruction",
        "category": "Lists",
        "newOpcode": "For each item # [VARIABLE] in [LIST] {BODY}",
        "inputTypes": {"BODY": "script"},
        "inputTranslation": {"SUBSTACK": "BODY"},
        "optionTypes": {"VARIABLE": "variable", "LIST": "list"},
    },
    "data_itemoflist": {
        "type": "stringReporter",
        "category": "Lists",
        "newOpcode": "item (INDEX) of [LIST]",
        "inputTypes": {"INDEX": "integer"},
        "optionTypes": {"LIST": "list"},
    },
    "data_itemnumoflist": {
        "type": "stringReporter",
        "category": "Lists",
        "newOpcode": "item # of (ITEM) in [LIST]",
        "inputTypes": {"ITEM": "text"},
        "optionTypes": {"LIST": "list"},
    },
    "data_amountinlist": {
        "type": "stringReporter",
        "category": "Lists",
        "newOpcode": "amount of (VALUE) of [LIST]",
        "inputTypes": {"VALUE": "text"},
        "optionTypes": {"LIST": "list"},
    },
    "data_lengthoflist": {
        "type": "stringReporter",
        "category": "Lists",
        "newOpcode": "length of [LIST]",
        "inputTypes": {},
        "optionTypes": {"LIST": "list"},
    },
    "data_listcontainsitem": {
        "type": "booleanReporter",
        "category": "Lists",
        "newOpcode": "[LIST] contains (ITEM) ?",
        "inputTypes": {"ITEM": "text"},
        "optionTypes": {"LIST": "list"},
    },
    "data_itemexistslist": {
        "type": "booleanReporter",
        "category": "Lists",
        "newOpcode": "item (INDEX) exists in [LIST] ?",
        "inputTypes": {"INDEX": "integer"},
        "optionTypes": {"LIST": "list"},
    },
    "data_listisempty": {
        "type": "booleanReporter",
        "category": "Lists",
        "newOpcode": "is [LIST] empty?",
        "inputTypes": {},
        "optionTypes": {"LIST": "list"},
    },
    "data_reverselist": {
        "type": "instruction",
        "category": "Lists",
        "newOpcode": "reverse [LIST]",
        "inputTypes": {},
        "optionTypes": {"LIST": "list"},
    },
    "data_arraylist": {
        "type": "instruction",
        "category": "Lists",
        "newOpcode": "set [LIST] to array (VALUE)",
        "inputTypes": {"VALUE": "text"},
        "optionTypes": {"LIST": "list"},
    },
    "data_listarray": {
        "type": "stringReporter",
        "category": "Lists",
        "newOpcode": "get list [LIST] as an array",
        "inputTypes": {},
        "optionTypes": {"LIST": "list"},
    },
    "data_showlist": {
        "type": "instruction",
        "category": "Lists",
        "newOpcode": "show list [LIST]",
        "inputTypes": {},
        "optionTypes": {"LIST": "list"},
    },
    "data_hidelist": {
        "type": "instruction",
        "category": "Lists",
        "newOpcode": "hide list [LIST]",
        "inputTypes": {},
        "optionTypes": {"LIST": "list"},
    },
}