opcodes = {
    "looks_sayforsecs": {
        "type": "intruction",
        "category": "Looks",
        "newOpcode": "say (MESSAGE) for (SECONDS) seconds",
        "inputTypes": {"MESSAGE": "text", "SECONDS": "number"},
        "inputTranslation": {"SECS": "SECONDS"},
        "optionTypes": {},
    },
    "looks_say": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "say (MESSAGE)",
        "inputTypes": {"MESSAGE": "text"},
        "optionTypes": {},
    },
    "looks_thinkforsecs": {
        "type": "intruction",
        "category": "Looks",
        "newOpcode": "think (MESSAGE) for (SECONDS) seconds",
        "inputTypes": {"MESSAGE": "text", "SECONDS": "number"},
        "inputTranslation": {"SECS": "SECONDS"},
        "optionTypes": {},
    },
    "looks_think": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "think (MESSAGE)",
        "inputTypes": {"MESSAGE": "text"},
        "optionTypes": {},
    },
    "looks_stoptalking": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "stop speaking",
        "inputTypes": {},
        "optionTypes": {},
    },
    "looks_setFont": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "set font to (FONT) with font size (FONT-SIZE)",
        "inputTypes": {"FONT": "text", "FONT-SIZE": "number"},
        "inputTranslation": {"font": "FONT", "size": "FONT-SIZE"},
        "optionTypes": {},
    },
    "looks_setColor": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "set [PROPERTY] color to (COLOR)",
        "inputTypes": {"COLOR": "color"},
        "inputTranslation": {"color": "COLOR"},
        "optionTypes": {"PROPERTY": "text bubble color property"},
        "optionTranslation": {"prop": "PROPERTY"},
    },
    "looks_setShape": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "set text bubble [PROPERTY] to (VALUE)",
        "inputTypes": {"VALUE": "number"},
        "inputTranslation": {"color": "VALUE"},
        "optionTypes": {"PROPERTY": "text bubble property"},
        "optionTranslation": {"prop": "PROPERTY"},
    },
    "looks_sayWidth": {
        "type": "stringReporter",
        "category": "Looks",
        "newOpcode": "bubble width",
        "inputTypes": {},
        "optionTypes": {},
        "canHaveMonitor": True,
    },
    "looks_sayHeight": {
        "type": "stringReporter",
        "category": "Looks",
        "newOpcode": "bubble height",
        "inputTypes": {},
        "optionTypes": {},
        "canHaveMonitor": True,
    },
    "looks_switchcostumeto": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "switch costume to ([COSTUME])",
        "inputTypes": {"COSTUME": "costume"},
        "optionTypes": {},
        "menus": [{"new": "COSTUME", "outer": "COSTUME", "inner": "COSTUME", "menuOpcode": "looks_costume"}],
    },
    "looks_nextcostume": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "next costume",
        "inputTypes": {},
        "optionTypes": {},
    },
    "looks_getinputofcostume": {
        "type": "stringReporter",
        "category": "Looks",
        "newOpcode": "([PROPERTY]) of ([COSTUME])",
        "inputTypes": {"PROPERTY": "costume property", "COSTUME": "costume"},
        "optionTypes": {},
        "menus": [
            {"new": "PROPERTY", "outer": "INPUT", "inner": "INPUT", "menuOpcode": "looks_getinput_menu"},
            {"new": "COSTUME", "outer": "COSTUME", "inner": "COSTUME", "menuOpcode": "looks_costume"},
        ],
    },
    "looks_switchbackdropto": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "switch backdrop to ([BACKDROP])",
        "inputTypes": {"BACKDROP": "backdrop"},
        "optionTypes": {},
        "menus": [{"new": "BACKDROP", "outer": "BACKDROP", "inner": "BACKDROP", "menuOpcode": "looks_backdrops"}],
    },
    "looks_nextbackdrop": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "next backdrop",
        "inputTypes": {},
        "optionTypes": {},
    },
    "looks_changesizeby": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "change size by (AMOUNT)",
        "inputTypes": {"AMOUNT": "number"},
        "inputTranslation": {"CHANGE": "AMOUNT"},
        "optionTypes": {},
    },
    "looks_setsizeto": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "set size to (SIZE)",
        "inputTypes": {"SIZE": "number"},
        "optionTypes": {},
    },
    "looks_setStretch": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "set stretch to x: (X) y: (Y)",
        "inputTypes": {"X": "number", "Y": "number"},
        "optionTypes": {},
    },
    "looks_stretchGetX": {
        "type": "stringReporter",
        "category": "Looks",
        "newOpcode": "x stretch",
        "inputTypes": {},
        "optionTypes": {},
        "canHaveMonitor": True,
    },
    "looks_stretchGetY": {
        "type": "stringReporter",
        "category": "Looks",
        "newOpcode": "y stretch",
        "inputTypes": {},
        "optionTypes": {},
        "canHaveMonitor": True,
    },
    "looks_changeeffectby": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "change [EFFECT] sprite effect by (AMOUNT)",
        "inputTypes": {"AMOUNT": "number"},
        "inputTranslation": {"CHANGE": "AMOUNT"},
        "optionTypes": {"EFFECT": "sprite effect"},
    },
    "looks_seteffectto": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "set [EFFECT] sprite effect to (VALUE)",
        "inputTypes": {"VALUE": "number"},
        "optionTypes": {"EFFECT": "sprite effect"},
    },
    "looks_setTintColor": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "set tint color to (COLOR)",
        "inputTypes": {"COLOR": "color"},
        "inputTranslation": {"color": "COLOR"},
        "optionTypes": {},
    },
    "looks_cleargraphiceffects": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "clear graphic effects",
        "inputTypes": {},
        "inputTranslation": {},
        "optionTypes": {},
    },
    "looks_getEffectValue": {
        "type": "stringReporter",
        "category": "Looks",
        "newOpcode": "[EFFECT] sprite effect",
        "inputTypes": {},
        "optionTypes": {"EFFECT": "sprite effect"},
        "canHaveMonitor": True,
    },
    "looks_tintColor": {
        "type": "stringReporter",
        "category": "Looks",
        "newOpcode": "tint color",
        "inputTypes": {},
        "optionTypes": {},
        "canHaveMonitor": True,
    },
    "looks_show": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "show",
        "inputTypes": {},
        "optionTypes": {},
    },
    "looks_hide": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "hide",
        "inputTypes": {},
        "optionTypes": {},
    },
    "looks_getSpriteVisible": {
        "type": "booleanReporter",
        "category": "Looks",
        "newOpcode": "visible?",
        "inputTypes": {},
        "optionTypes": {},
        "canHaveMonitor": True,
    },
    "looks_changeVisibilityOfSpriteShow": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "show ([TARGET])",
        "inputTypes": {"TARGET": "myself || other sprite"},
        "optionTypes": {},
        "menus": [{"new": "TARGET", "outer": "VISIBLE_OPTION", "inner": "VISIBLE_OPTION", "menuOpcode": "looks_changeVisibilityOfSprite_menu"}],
    },
    "looks_changeVisibilityOfSpriteHide": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "hide ([TARGET])",
        "inputTypes": {"TARGET": "myself || other sprite"},
        "optionTypes": {},
        "menus": [{"new": "TARGET", "outer": "VISIBLE_OPTION", "inner": "VISIBLE_OPTION", "menuOpcode": "looks_changeVisibilityOfSprite_menu"}],
    },    
    "looks_getOtherSpriteVisible": {
        "type": "booleanReporter", 
        "category": "Looks",
        "newOpcode": "is ([TARGET]) visible?",
        "inputTypes": {"TARGET": "myself || other sprite"},
        "optionTypes": {},
        "menus": [{"new": "TARGET", "outer": "VISIBLE_OPTION", "inner": "VISIBLE_OPTION", "menuOpcode": "looks_getOtherSpriteVisible_menu"}],
    },
    "looks_gotofrontback": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "go to [LAYER] layer",
        "inputTypes": {},
        "optionTypes": {"LAYER": "front|back"},
        "optionTranslation": {"FRONT_BACK": "LAYER"},
    },
    "looks_goforwardbackwardlayers": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "go [DIRECTION] (LAYERS) layers",
        "inputTypes": {"LAYERS": "integer"},
        "inputTranslation": {"NUM": "LAYERS"},
        "optionTypes": {"DIRECTION": "forward|backward"},
        "optionTranslation": {"FORWARD_BACKWARD": "DIRECTION"},
    },
    "looks_layersSetLayer": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "go to layer (LAYER)",
        "inputTypes": {"LAYER": "integer"},
        "inputTranslation": {"NUM": "LAYER"},
        "optionTypes": {},
    },
    "looks_goTargetLayer": {
        "type": "instruction",
        "category": "Looks",
        "newOpcode": "go [DIRECTION] ([TARGET])",
        "inputTypes": {"TARGET": "myself || other sprite"},
        "optionTypes": {"DIRECTION": "infront|behind"},
        "optionTranslation": {"FORWARD_BACKWARD": "DIRECTION"},
        "menus": [{"new": "TARGET", "outer": "VISIBLE_OPTION", "inner": "VISIBLE_OPTION", "menuOpcode": "looks_getOtherSpriteVisible_menu"}],
    },
    "looks_layersGetLayer": {
        "type": "stringReporter",
        "category": "Looks",
        "newOpcode": "layer",
        "inputTypes": {},
        "optionTypes": {},
        "canHaveMonitor": True,
    },
    "looks_costumenumbername": {
        "type": "stringReporter",
        "category": "Looks",
        "newOpcode": "costume [PROPERTY]",
        "inputTypes": {},
        "optionTypes": {"PROPERTY": "number|name"},
        "optionTranslation": {"NUMBER_NAME": "PROPERTY"},
        "canHaveMonitor": True,
    },
    "looks_backdropnumbername": {
        "type": "stringReporter",
        "category": "Looks",
        "newOpcode": "backdrop [PROPERTY]",
        "inputTypes": {},
        "optionTypes": {"PROPERTY": "number|name"},
        "optionTranslation": {"NUMBER_NAME": "PROPERTY"},
        "canHaveMonitor": True,
    },
    "looks_size": {
        "type": "stringReporter",
        "category": "Looks",
        "newOpcode": "size",
        "inputTypes": {},
        "optionTypes": {},
        "canHaveMonitor": True,
    },
}