{
    "targets": [
        {
            "isStage": True,
            "name": "Stage",
            "variables": {},
            "lists": {},
            "broadcasts": {},
            "customVars": [],
            "blocks": {},
            "comments": {},
            "currentCostume": 0,
            "costumes": [
                {
                    "name": "empty",
                    "dataFormat": "svg",
                    "assetId": "3bd13a3366c1a32c114051253de8afdd",
                    "md5ext": "3bd13a3366c1a32c114051253de8afdd.svg",
                    "rotationCenterX": 240,
                    "rotationCenterY": 180,
                },
            ],
            "sounds": [],
            "id": "Qg`inAkI`?tY/Vqn|(Xh",
            "volume": 100,
            "layerOrder": 0,
            "tempo": 60,
            "videoTransparency": 50,
            "videoState": "on",
            "textToSpeechLanguage": None,
            "extensionData": {},
        },
        {
            "isStage": False,
            "name": "my_Sprite",
            "variables": {},
            "lists": {},
            "broadcasts": {},
            "customVars": [],
            "blocks": {
                "a": {
                    "opcode": "control_if",
                    "next": None,
                    "parent": None,
                    "inputs": {
                        "CONDITION": [2, "b"],
                    },
                    "fields": {},
                    "shadow": False,
                    "topLevel": True,
                    "x": 0,
                    "y": 0,
                },
                "b": {
                    "opcode": "checkbox",
                    "next": None,
                    "parent": "a",
                    "inputs": {},
                    "fields": {
                        "CHECKBOX": ["TRUE", "*`L724f50w[kWc;|D6kr"],
                    },
                    "shadow": False,
                    "topLevel": False,
                },
                "c": {
                    "opcode": "control_expandableIf",
                    "next": None,
                    "parent": None,
                    "inputs": {
                        "BOOL1": [1, "d"],
                    },
                    "fields": {
                        "REMOVE": ["", "s,1R)zi|ZY#dM2Y@I{Wi"],
                        "ADD": ["", "JjH~rJbBQXOJY8S1HBGY"],
                    },
                    "shadow": False,
                    "topLevel": True,
                    "x": 279,
                    "y": 0,
                    "mutation": {
                        "tagName": "mutation",
                        "children": [],
                        "branches": "1",
                        "ends-in-else": "false",
                    },
                },
                "d": {
                    "opcode": "checkbox",
                    "next": None,
                    "parent": "c",
                    "inputs": {},
                    "fields": {
                        "CHECKBOX": ["FALSE", "H3?vh%XU1,7KXMTWR.R/"],
                    },
                    "shadow": True,
                    "topLevel": False,
                },
                "e": {
                    "opcode": "control_repeat_until",
                    "next": None,
                    "parent": None,
                    "inputs": {
                        "CONDITION": [1, "f"],
                    },
                    "fields": {},
                    "shadow": False,
                    "topLevel": True,
                    "x": 89,
                    "y": 164,
                },
                "f": {
                    "opcode": "checkbox",
                    "next": None,
                    "parent": "e",
                    "inputs": {},
                    "fields": {
                        "CHECKBOX": ["FALSE", "JenBM#E_D^cXFM.?nI`7"],
                    },
                    "shadow": True,
                    "topLevel": False,
                },
            },
            "comments": {},
            "currentCostume": 0,
            "costumes": [
                {
                    "name": "empty",
                    "dataFormat": "svg",
                    "assetId": "3bd13a3366c1a32c114051253de8afdd",
                    "md5ext": "3bd13a3366c1a32c114051253de8afdd.svg",
                    "rotationCenterX": 240,
                    "rotationCenterY": 180,
                },
            ],
            "sounds": [],
            "id": "Qg`in=iyuTw#d|w{O[b;",
            "volume": 100,
            "layerOrder": 1,
            "visible": True,
            "x": 0,
            "y": 0,
            "size": 100,
            "direction": 90,
            "draggable": False,
            "rotationStyle": "all around",
            "extensionData": {},
        },
    ],
    "monitors": [],
    "extensionData": {},
    "extensions": [],
    "meta": {
        "semver": "3.0.0",
        "vm": "0.2.0",
        "origin": "PenguinMod",
        "agent": "",
        "platform": {
            "name": "PenguinMod",
            "url": "https://penguinmod.com/",
            "version": "stable",
        },
    },
}