FRProject(
    targets=[
        FRStage(
            tempo=60,
            video_transparency=50,
            video_state="on",
            text_to_speech_language=None,
            is_stage=True,
            name="Stage",
            variables={
                "`jEk@4|i[#Fk?(8x)AV.-my variable": ("my variable", 0),
            },
            lists={},
            broadcasts={},
            custom_vars=[],
            blocks={},
            comments={},
            current_costume=0,
            costumes=[
                FRCostume(
                    name="backdrop1",
                    asset_id="cd21514d0531fdffb22204e0ec5ed84a",
                    data_format="svg",
                    md5ext="cd21514d0531fdffb22204e0ec5ed84a.svg",
                    rotation_center_x=240,
                    rotation_center_y=180,
                    bitmap_resolution=None,
                ),
            ],
            sounds=[],
            id="p]_uD8#0^Q=ryfqeQLud",
            volume=100,
            layer_order=0,
        ),
        FRSprite(
            visible=True,
            x=0,
            y=0,
            size=100,
            direction=90,
            draggable=False,
            rotation_style="all around",
            is_stage=False,
            name="Sprite1",
            variables={},
            lists={},
            broadcasts={},
            custom_vars=[],
            blocks={
                "a": FRBlock(
                    opcode="pen_drawComplexShape",
                    next=None,
                    parent=None,
                    inputs={
                        "SHAPE": (1, "b"),
                        "COLOR": (1, (9, "#d0d228")),
                    },
                    fields={},
                    shadow=False,
                    top_level=True,
                    x=202,
                    y=333,
                    comment=None,
                    mutation=None,
                ),
                "b": FRBlock(
                    opcode="polygon",
                    next=None,
                    parent="a",
                    inputs={
                        "x1": (2, (4, "-43.30127018922194")),
                        "y1": (2, (4, "-24.999999999999996")),
                        "x2": (2, (4, "43.30127018922194")),
                        "y2": (2, (4, "-24.999999999999996")),
                        "x3": (2, (4, "3.061616997868383e-15")),
                        "y3": (2, (4, "50")),
                    },
                    fields={
                        "button": (False, "0/A%bk{_wuR#2+CB`#NC"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRPolygonMutation(
                        points=3,
                        color="#0FBD8C",
                        midle=[0, 0],
                        scale=50,
                        expanded=True,
                        needs_init=True,
                        tag_name="mutation",
                        children=[],
                    ),
                ),
                "c": FRBlock(
                    opcode="pen_draw4SidedComplexShape",
                    next=None,
                    parent=None,
                    inputs={
                        "SHAPE": (1, "d"),
                        "COLOR": (1, (9, "#06e27a")),
                    },
                    fields={},
                    shadow=False,
                    top_level=True,
                    x=442,
                    y=449,
                    comment=None,
                    mutation=None,
                ),
                "d": FRBlock(
                    opcode="polygon",
                    next=None,
                    parent="c",
                    inputs={
                        "x1": (2, (4, "-35.35533905932737")),
                        "y1": (2, (4, "-35.35533905932738")),
                        "x2": (2, (4, "35.35533905932738")),
                        "y2": (2, (4, "-35.35533905932737")),
                        "x3": (2, (4, "35.35533905932738")),
                        "y3": (2, (4, "35.35533905932737")),
                        "x4": (2, (4, "-35.35533905932737")),
                        "y4": (2, (4, "35.35533905932738")),
                    },
                    fields={
                        "button": (False, "P%!uK,#683YB|r~!(ilZ"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRPolygonMutation(
                        points=4,
                        color="#0FBD8C",
                        midle=[0, 0],
                        scale=50,
                        expanded=True,
                        needs_init=True,
                        tag_name="mutation",
                        children=[],
                    ),
                ),
                "e": FRBlock(
                    opcode="pen_drawComplexShape",
                    next=None,
                    parent=None,
                    inputs={
                        "SHAPE": (1, "f"),
                        "COLOR": (1, (9, "#c95312")),
                    },
                    fields={},
                    shadow=False,
                    top_level=True,
                    x=615,
                    y=602,
                    comment=None,
                    mutation=None,
                ),
                "f": FRBlock(
                    opcode="polygon",
                    next=None,
                    parent="e",
                    inputs={
                        "x1": (2, (4, "-43.30127018922194")),
                        "y1": (2, (4, "-24.999999999999996")),
                        "x2": (2, (4, "43.30127018922194")),
                        "y2": (2, (4, "-24.999999999999996")),
                        "x3": (2, (4, "3.061616997868383e-15")),
                        "y3": (2, (4, "50")),
                    },
                    fields={
                        "button": (True, "7V}BE_TRUt[tC:j*v5Ck"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRPolygonMutation(
                        points=3,
                        color="#0FBD8C",
                        midle=[0, 0],
                        scale=50,
                        expanded=True,
                        needs_init=True,
                        tag_name="mutation",
                        children=[],
                    ),
                ),
            },
            comments={},
            current_costume=0,
            costumes=[
                FRCostume(
                    name="costume1",
                    asset_id="c434b674f2da18ba13cdfe51dbc05ecc",
                    data_format="svg",
                    md5ext="c434b674f2da18ba13cdfe51dbc05ecc.svg",
                    rotation_center_x=26,
                    rotation_center_y=46,
                    bitmap_resolution=1,
                ),
            ],
            sounds=[
                FRSound(
                    name="Squawk",
                    asset_id="e140d7ff07de8fa35c3d1595bba835ac",
                    data_format="wav",
                    md5ext="e140d7ff07de8fa35c3d1595bba835ac.wav",
                    rate=48000,
                    sample_count=17867,
                ),
            ],
            id="5I9nI;7P)jdiR-_X;/%l",
            volume=100,
            layer_order=1,
        ),
    ],
    monitors=[],
    extension_data={},
    extensions=["theshovelcanvaseffects", "pen"],
    extension_urls=KeyReprDict(keys={"pen"}),
    meta=FRMeta(
        semver="3.0.0",
        vm="0.2.0",
        agent="",
        platform=FRPenguinModPlatformMeta(name="PenguinMod", url="https://penguinmod.com/", version="stable"),
    ),
    asset_files=KeyReprDict(keys={"cd21514d0531fdffb22204e0ec5ed84a.svg", "c434b674f2da18ba13cdfe51dbc05ecc.svg", "e140d7ff07de8fa35c3d1595bba835ac.wav"}),
)