FRProject(
    targets=[FRStage(
            tempo=60,
            video_transparency=50,
            video_state="on",
            text_to_speech_language=None,
            is_stage=True,
            name="Stage",
            variables={
                "`jEk@4|i[#Fk?(8x)AV.-my variable": ("my variable", 0),
            },
            lists={},
            broadcasts={},
            custom_vars=[],
            blocks={},
            comments={},
            current_costume=0,
            costumes=[FRCostume(
                    name="backdrop1",
                    asset_id="cd21514d0531fdffb22204e0ec5ed84a",
                    data_format="svg",
                    md5ext="cd21514d0531fdffb22204e0ec5ed84a.svg",
                    rotation_center_x=240,
                    rotation_center_y=180,
                    bitmap_resolution=None,
                )],
            sounds=[],
            id="p]_uD8#0^Q=ryfqeQLud",
            volume=100,
            layer_order=0,
        ), FRSprite(
            visible=True,
            x=0,
            y=0,
            size=100,
            direction=90,
            draggable=False,
            rotation_style="all around",
            is_stage=False,
            name="Sprite1",
            variables={},
            lists={},
            broadcasts={},
            custom_vars=[],
            blocks={
                "d": FRBlock(
                    opcode="procedures_definition",
                    next=None,
                    parent=None,
                    inputs={
                        "custom_block": (1, "a"),
                    },
                    fields={},
                    shadow=False,
                    top_level=True,
                    x=44,
                    y=44,
                    comment=None,
                    mutation=None,
                ),
                "a": FRBlock(
                    opcode="procedures_prototype",
                    next=None,
                    parent="d",
                    inputs={
                        ")OXNsC`?|lNv5wj-:6]L": (1, "e"),
                        "(w$eOoy@,abdEX21.ES/": (1, "f"),
                    },
                    fields={},
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRCustomBlockMutation(
                        proccode="block name %s %b",
                        argument_ids=[")OXNsC`?|lNv5wj-:6]L", "(w$eOoy@,abdEX21.ES/"],
                        argument_names=["not", "bbm"],
                        argument_defaults=["", "false"],
                        warp=False,
                        returns=None,
                        edited=True,
                        optype=None,
                        color=("#FF6680", "#FF4D6A", "#FF3355"),
                        tag_name="mutation",
                        children=[],
                    ),
                ),
                "e": FRBlock(
                    opcode="argument_reporter_string_number",
                    next=None,
                    parent="a",
                    inputs={},
                    fields={
                        "VALUE": ("not", "xqAllnAU[_zYRcZ(2E|V"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRCustomBlockArgumentMutation(color=("#FF6680", "#FF4D6A", "#FF3355"), tag_name="mutation", children=[]),
                ),
                "f": FRBlock(
                    opcode="argument_reporter_boolean",
                    next=None,
                    parent="a",
                    inputs={},
                    fields={
                        "VALUE": ("bbm", "g#@hJYJA/!yGAbJ@sHD~"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRCustomBlockArgumentMutation(color=("#FF6680", "#FF4D6A", "#FF3355"), tag_name="mutation", children=[]),
                ),
                "j": FRBlock(
                    opcode="argument_reporter_string_number",
                    next=None,
                    parent=None,
                    inputs={},
                    fields={
                        "VALUE": ("not", "t]5vcbNm4}wFkm[Eu,)e"),
                    },
                    shadow=False,
                    top_level=True,
                    x=174,
                    y=265,
                    comment=None,
                    mutation=FRCustomBlockArgumentMutation(color=("#FF6680", "#FF4D6A", "#FF3355"), tag_name="mutation", children=[]),
                ),
                "k": FRBlock(
                    opcode="argument_reporter_boolean",
                    next=None,
                    parent=None,
                    inputs={},
                    fields={
                        "VALUE": ("bbm", ":zNT-}rH[2tDO@(lif|b"),
                    },
                    shadow=False,
                    top_level=True,
                    x=281,
                    y=334,
                    comment=None,
                    mutation=FRCustomBlockArgumentMutation(color=("#FF6680", "#FF4D6A", "#FF3355"), tag_name="mutation", children=[]),
                ),
                "c": FRBlock(
                    opcode="procedures_definition_return",
                    next="g",
                    parent=None,
                    inputs={
                        "custom_block": (1, "b"),
                    },
                    fields={},
                    shadow=False,
                    top_level=True,
                    x=552,
                    y=115,
                    comment=None,
                    mutation=None,
                ),
                "b": FRBlock(
                    opcode="procedures_prototype",
                    next=None,
                    parent="c",
                    inputs={
                        "+bN7ah1O^]`@NR=*0HRE": (1, "h"),
                        "o=OFC,4/;MS?Q6IUT;9Q": (1, "i"),
                    },
                    fields={},
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRCustomBlockMutation(
                        proccode="sdf %s %b",
                        argument_ids=["+bN7ah1O^]`@NR=*0HRE", "o=OFC,4/;MS?Q6IUT;9Q"],
                        argument_names=["number or text", "sdf bo"],
                        argument_defaults=["", "", "false"],
                        warp=False,
                        returns=True,
                        edited=True,
                        optype="string",
                        color=("#FF6680", "#eb3d5b", "#df2847"),
                        tag_name="mutation",
                        children=[],
                    ),
                ),
                "h": FRBlock(
                    opcode="argument_reporter_string_number",
                    next=None,
                    parent="b",
                    inputs={},
                    fields={
                        "VALUE": ("number or text", "N6tPJf1tB-xD0,n3DE{w"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRCustomBlockArgumentMutation(color=("#FF6680", "#FF4D6A", "#FF3355"), tag_name="mutation", children=[]),
                ),
                "g": FRBlock(
                    opcode="procedures_return",
                    next=None,
                    parent="c",
                    inputs={
                        "return": (1, (10, "1")),
                    },
                    fields={},
                    shadow=False,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=None,
                ),
                "l": FRBlock(
                    opcode="argument_reporter_string_number",
                    next=None,
                    parent=None,
                    inputs={},
                    fields={
                        "VALUE": ("number or text", "zV_bUL2w!p^zi@KjM)l_"),
                    },
                    shadow=False,
                    top_level=True,
                    x=662,
                    y=330,
                    comment=None,
                    mutation=FRCustomBlockArgumentMutation(color=("#FF6680", "#FF4D6A", "#FF3355"), tag_name="mutation", children=[]),
                ),
                "m": FRBlock(
                    opcode="argument_reporter_string_number",
                    next=None,
                    parent="a",
                    inputs={},
                    fields={
                        "VALUE": ("not", "+j!QTJ@Xs,bZ4qW#|EQ*"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRCustomBlockArgumentMutation(color=("#FF6680", "#FF4D6A", "#FF3355"), tag_name="mutation", children=[]),
                ),
                "n": FRBlock(
                    opcode="argument_reporter_boolean",
                    next=None,
                    parent="a",
                    inputs={},
                    fields={
                        "VALUE": ("bbm", "U3]/!O`Y.~-TV;sUh~6t"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRCustomBlockArgumentMutation(color=("#FF6680", "#FF4D6A", "#FF3355"), tag_name="mutation", children=[]),
                ),
                "o": FRBlock(
                    opcode="argument_reporter_string_number",
                    next=None,
                    parent="b",
                    inputs={},
                    fields={
                        "VALUE": ("number or text", "yl4vBY[7i)b~UT+sJQde"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRCustomBlockArgumentMutation(color=("#FF6680", "#FF4D6A", "#FF3355"), tag_name="mutation", children=[]),
                ),
                "i": FRBlock(
                    opcode="argument_reporter_boolean",
                    next=None,
                    parent="b",
                    inputs={},
                    fields={
                        "VALUE": ("sdf bo", "tnqPbZq*BapNxwQ/{h1_"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRCustomBlockArgumentMutation(color=("#FF6680", "#eb3d5b", "#df2847"), tag_name="mutation", children=[]),
                ),
            },
            comments={},
            current_costume=0,
            costumes=[FRCostume(
                    name="costume1",
                    asset_id="c434b674f2da18ba13cdfe51dbc05ecc",
                    data_format="svg",
                    md5ext="c434b674f2da18ba13cdfe51dbc05ecc.svg",
                    rotation_center_x=26,
                    rotation_center_y=46,
                    bitmap_resolution=1,
                )],
            sounds=[FRSound(
                    name="Squawk",
                    asset_id="e140d7ff07de8fa35c3d1595bba835ac",
                    data_format="wav",
                    md5ext="e140d7ff07de8fa35c3d1595bba835ac.wav",
                    rate=48000,
                    sample_count=17867,
                )],
            id="5I9nI;7P)jdiR-_X;/%l",
            volume=100,
            layer_order=1,
        )],
    monitors=[],
    extension_data={},
    extensions=[],
    extension_urls=KeyReprDict(keys={}),
    meta=FRMeta(
        semver="3.0.0",
        vm="0.2.0",
        agent="",
        platform=FRPenguinModPlatformMeta(name="PenguinMod", url="https://penguinmod.com/", version="stable"),
    ),
    asset_files=KeyReprDict(keys={
        "cd21514d0531fdffb22204e0ec5ed84a.svg",
        "c434b674f2da18ba13cdfe51dbc05ecc.svg",
        "e140d7ff07de8fa35c3d1595bba835ac.wav",
    }),
)