FRProject(
    targets=[
        FRStage(
            tempo=60,
            video_transparency=50,
            video_state="on",
            text_to_speech_language=None,
            is_stage=True,
            name="Stage",
            variables={
                "nAkIUqJYAP#jU[:mkdOm": ("my variable", 0),
            },
            lists={},
            broadcasts={},
            custom_vars=[],
            blocks={},
            comments={},
            current_costume=0,
            costumes=[
                FRCostume(
                    name="backdrop1",
                    asset_id="3bd13a3366c1a32c114051253de8afdd",
                    data_format="svg",
                    md5ext="3bd13a3366c1a32c114051253de8afdd.svg",
                    rotation_center_x=240,
                    rotation_center_y=180,
                    bitmap_resolution=None,
                ),
            ],
            sounds=[],
            id="Qg`inAkI`?tY/Vqn|(Xh",
            volume=100,
            layer_order=0,
        ),
        FRSprite(
            visible=True,
            x=0,
            y=0,
            size=100,
            direction=90,
            draggable=False,
            rotation_style="all around",
            is_stage=False,
            name="Sprite1",
            variables={},
            lists={},
            broadcasts={},
            custom_vars=[],
            blocks={
                "b": FRBlock(
                    opcode="polygon",
                    next=None,
                    parent="b",
                    inputs={
                        "x1": (1, (4, "-43.30127018922194")),
                        "y1": (1, (4, "-24.999999999999996")),
                        "x2": (1, (4, "43.30127018922194")),
                        "y2": (1, (4, "-24.999999999999996")),
                        "x3": (1, (4, "3.061616997868383e-15")),
                        "y3": (1, (4, "93.39")),
                    },
                    fields={
                        "button": (False, "Jn?ltj/FovFTfg;cBptN"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRPolygonMutation(
                        points=3,
                        color="#0FBD8C",
                        midle=[0, 0],
                        scale=50,
                        expanded=True,
                        needs_init=True,
                        tag_name="mutation",
                        children=[],
                    ),
                ),
                "a": FRBlock(
                    opcode="pen_drawComplexShape",
                    next=None,
                    parent=None,
                    inputs={
                        "SHAPE": (1, "b"),
                        "COLOR": (1, (9, "#d0d228")),
                    },
                    fields={},
                    shadow=False,
                    top_level=True,
                    x=202,
                    y=333,
                    comment=None,
                    mutation=None,
                ),
                "d": FRBlock(
                    opcode="polygon",
                    next=None,
                    parent="d",
                    inputs={
                        "x1": (1, (4, "-35.35533905932737")),
                        "y1": (1, (4, "-35.35533905932738")),
                        "x2": (1, (4, "35.35533905932738")),
                        "y2": (1, (4, "-35.35533905932737")),
                        "x3": (1, (4, "35.35533905932738")),
                        "y3": (1, (4, "35.35533905932737")),
                        "x4": (1, (4, "-35.35533905932737")),
                        "y4": (1, (4, "35.35533905932738")),
                    },
                    fields={
                        "button": (False, "Jn?ltj/FovFTfg;cBptN"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRPolygonMutation(
                        points=4,
                        color="#0FBD8C",
                        midle=[0, 0],
                        scale=50,
                        expanded=True,
                        needs_init=True,
                        tag_name="mutation",
                        children=[],
                    ),
                ),
                "c": FRBlock(
                    opcode="pen_draw4SidedComplexShape",
                    next=None,
                    parent=None,
                    inputs={
                        "SHAPE": (1, "d"),
                        "COLOR": (1, (9, "#06e27a")),
                    },
                    fields={},
                    shadow=False,
                    top_level=True,
                    x=442,
                    y=449,
                    comment=None,
                    mutation=None,
                ),
                "f": FRBlock(
                    opcode="polygon",
                    next=None,
                    parent="f",
                    inputs={
                        "x1": (1, (4, "-43.30127018922194")),
                        "y1": (1, (4, "-24.999999999999996")),
                        "x2": (1, (4, "43.30127018922194")),
                        "y2": (1, (4, "-24.999999999999996")),
                        "x3": (1, (4, "3.061616997868383e-15")),
                        "y3": (1, (4, "50")),
                    },
                    fields={
                        "button": (True, "Jn?l-I+TBF!=^xxqS,b^"),
                    },
                    shadow=True,
                    top_level=False,
                    x=None,
                    y=None,
                    comment=None,
                    mutation=FRPolygonMutation(
                        points=3,
                        color="#0FBD8C",
                        midle=[0, 0],
                        scale=50,
                        expanded=True,
                        needs_init=True,
                        tag_name="mutation",
                        children=[],
                    ),
                ),
                "e": FRBlock(
                    opcode="pen_drawComplexShape",
                    next=None,
                    parent=None,
                    inputs={
                        "SHAPE": (1, "f"),
                        "COLOR": (1, (9, "#c95312")),
                    },
                    fields={},
                    shadow=False,
                    top_level=True,
                    x=615,
                    y=602,
                    comment=None,
                    mutation=None,
                ),
            },
            comments={},
            current_costume=0,
            costumes=[
                FRCostume(
                    name="costume1",
                    asset_id="f4253348baa568f73dbfec5a2978be14",
                    data_format="svg",
                    md5ext="f4253348baa568f73dbfec5a2978be14.svg",
                    rotation_center_x=26,
                    rotation_center_y=46,
                    bitmap_resolution=None,
                ),
            ],
            sounds=[
                FRSound(
                    name="Squawk",
                    asset_id="e140d7ff07de8fa35c3d1595bba835ac",
                    data_format="wav",
                    md5ext="e140d7ff07de8fa35c3d1595bba835ac.wav",
                    rate=22050,
                    sample_count=8208,
                ),
            ],
            id="Qg`ioTDHQbL~wA;YdpAy",
            volume=100,
            layer_order=1,
        ),
    ],
    monitors=[],
    extension_data={},
    extensions=["theshovelcanvaseffects", "pen"],
    extension_urls=KeyReprDict(keys={"pen"}),
    meta=FRMeta(
        semver="3.0.0",
        vm="0.2.0",
        agent="",
        platform=FRPenguinModPlatformMeta(name="PenguinMod", url="https://penguinmod.com/", version="stable"),
    ),
    asset_files=KeyReprDict(keys={"3bd13a3366c1a32c114051253de8afdd.svg", "f4253348baa568f73dbfec5a2978be14.svg", "e140d7ff07de8fa35c3d1595bba835ac.wav"}),
)