from __future__ import annotations
import pytest
from pmp_manip.otility.base import AbstractTreePath, grepr_dataclass, field


class TestAbstractTreePath:
    """Test AbstractTreePath class."""
    
    def test_empty_path(self):
        """Test creating an empty path."""
        path = AbstractTreePath()
        assert len(path) == 0
        assert str(path) == "AbstractTreePath()"
    
    def test_add_attribute(self):
        """Test adding an attribute to the path."""
        path = AbstractTreePath()
        new_path = path.add_attribute("name")
        assert len(new_path) == 1
        assert ".name" in repr(new_path)
    
    def test_add_attribute_chain(self):
        """Test chaining multiple attribute additions."""
        path = AbstractTreePath()
        new_path = path.add_attribute("obj").add_attribute("field")
        assert len(new_path) == 2
        assert ".obj" in repr(new_path)
        assert ".field" in repr(new_path)
    
    def test_add_index_or_key_int(self):
        """Test adding an integer index."""
        path = AbstractTreePath()
        new_path = path.add_index_or_key(0)
        assert len(new_path) == 1
        assert "[0]" in repr(new_path)
    
    def test_add_index_or_key_str(self):
        """Test adding a string key."""
        path = AbstractTreePath()
        new_path = path.add_index_or_key("key")
        assert len(new_path) == 1
        assert '["key"]' in repr(new_path) or "['key']" in repr(new_path)
    
    def test_add_index_or_key_chain(self):
        """Test chaining indices and keys."""
        path = AbstractTreePath()
        new_path = path.add_index_or_key(0).add_index_or_key("key").add_index_or_key(5)
        assert len(new_path) == 3
    
    def test_path_immutability(self):
        """Test that paths are immutable."""
        path = AbstractTreePath()
        new_path = path.add_attribute("test")
        assert len(path) == 0  # Original unchanged
        assert len(new_path) == 1
    
    def test_path_with_dot_start(self):
        """Test path created with start_with_dot=True."""
        path = AbstractTreePath(start_with_dot=True).add_attribute("value")
        path_str = str(path)
        assert "." in path_str or path_str == "."


class TestGreprDataclass:
    """Test grepr_dataclass decorator."""
    
    def test_grepr_dataclass_basic(self):
        """Test basic grepr_dataclass functionality."""
        @grepr_dataclass()
        class TestClass:
            name: str
            value: int
        
        obj = TestClass(name="test", value=42)
        assert obj.name == "test"
        assert obj.value == 42
    
    def test_grepr_dataclass_with_defaults(self):
        """Test grepr_dataclass with default values."""
        @grepr_dataclass()
        class TestClass:
            name: str
            value: int = 10
        
        obj = TestClass(name="test")
        assert obj.value == 10
    
    def test_grepr_dataclass_repr(self):
        """Test that repr is overridden."""
        @grepr_dataclass()
        class TestClass:
            name: str
        
        obj = TestClass(name="test")
        repr_str = repr(obj)
        assert "TestClass" in repr_str
        assert "name" in repr_str
        assert "test" in repr_str
    
    def test_grepr_dataclass_frozen(self):
        """Test frozen grepr_dataclass."""
        @grepr_dataclass(frozen=True)
        class FrozenClass:
            value: int
        
        obj = FrozenClass(value=42)
        assert obj.value == 42
    
    def test_grepr_dataclass_no_init(self):
        """Test grepr_dataclass with init=False."""
        @grepr_dataclass(init=False)
        class NoInitClass:
            value: int = 10

        # init=False means no __init__ is generated by dataclass
        # So we can't use the normal constructor
        # But we can manually create instances if needed
        obj = object.__new__(NoInitClass)
        obj.value = 42
        assert obj.value == 42
    
    def test_grepr_dataclass_validate(self):
        """Test that validate method exists."""
        @grepr_dataclass(validate=True)
        class ValidatedClass:
            name: str
            count: int
        
        obj = ValidatedClass(name="test", count=5)
        # Should have validate method
        assert hasattr(obj, 'validate')
        assert callable(obj.validate)
        
        # Validate should not raise for correct types
        obj.validate()


class TestField:
    """Test the custom field function."""
    
    def test_field_basic_creation(self):
        """Test basic field creation."""
        f = field()
        assert f is not None
    
    def test_field_with_default(self):
        """Test field with default value."""
        f = field(default=42)
        assert f.default == 42
    
    def test_field_with_default_factory(self):
        """Test field with default factory."""
        f = field(default_factory=list)
        assert callable(f.default_factory)
    
    def test_field_grepr_option(self):
        """Test field with grepr option."""
        f = field(grepr=False)
        assert f is not None
    
    def test_field_in_dataclass(self):
        """Test using field in a dataclass."""
        @grepr_dataclass()
        class TestClass:
            items: list = field(default_factory=list)
            name: str = field(default="default")
        
        obj = TestClass()
        assert obj.items == []
        assert obj.name == "default"
