from pytest import fixture, raises

from pypenguin.utility import ThanksError

from pypenguin.core.monitor import FRMonitor

ALL_FR_MONITOR_DATAS = [
    { # [0]
        "height": 0,
        "id": "5I9nI;7P)jdiR-_X;/%l_xposition",
        "isDiscrete": True,
        "mode": "default",
        "opcode": "motion_xposition",
        "params": {},
        "sliderMax": 100,
        "sliderMin": 0,
        "spriteName": "Sprite1",
        "value": 0,
        "visible": True,
        "width": 0,
        "x": 5,
        "y": 5,
    },
    { # [1]
        "height": 0,
        "id": "5I9nI;7P)jdiR-_X;/%l_yposition",
        "isDiscrete": True,
        "mode": "default",
        "opcode": "motion_yposition",
        "params": {},
        "sliderMax": 100,
        "sliderMin": 0,
        "spriteName": "Sprite1",
        "value": 0,
        "visible": True,
        "width": 0,
        "x": 5,
        "y": 31,
    },
    { # [2]
        "height": 0,
        "id": "$6=c?qlc|4Q*mK{XGC}z",
        "isDiscrete": False,
        "mode": "slider",
        "opcode": "data_variable",
        "params": {"VARIABLE": "globl"},
        "sliderMax": 100,
        "sliderMin": -50.3,
        "spriteName": None,
        "value": 0,
        "visible": True,
        "width": 0,
        "x": 110,
        "y": 76,
    },
    { # [3]
        "height": 0,
        "id": "P4dp6h[X1|F3dYA4I?C`",
        "isDiscrete": True,
        "mode": "default",
        "opcode": "data_variable",
        "params": {"VARIABLE": "globl2"},
        "sliderMax": 100,
        "sliderMin": -20,
        "spriteName": None,
        "value": 0,
        "visible": True,
        "width": 0,
        "x": 216,
        "y": 128,
    },
    { # [4]
        "height": 198,
        "id": "ru2NZobs(r+b[~|-rTCf",
        "mode": "list",
        "opcode": "data_listcontents",
        "params": {"LIST": "locl"},
        "spriteName": "Sprite1",
        "value": [],
        "visible": True,
        "width": 100,
        "x": 342,
        "y": 15,
    },
    { # [5]
       "height": 147,
       "id": "Zc!aC=9=36YS+pEb?kWj",
       "mode": "list",
       "opcode": "data_listcontents",
       "params": {"LIST": "globl"},
       "spriteName": None,
       "value": [],
       "visible": True,
       "width": 176,
       "x": 36,
       "y": 153,
    },
    { # [6]
        "height": 0,
        "id": "8kv=.#:+,mIq:M5++hvu",
        "isDiscrete": True,
        "mode": "default",
        "opcode": "data_variable",
        "params": {"VARIABLE": "locl"},
        "sliderMax": 100,
        "sliderMin": 0,
        "spriteName": "Sprite1",
        "value": 0,
        "visible": True,
        "width": 0,
        "x": 52,
        "y": 120,
    },
    { # [7]
        "height": 0,
        "id": "sensing_mousedown",
        "isDiscrete": True,
        "mode": "default",
        "opcode": "sensing_mousedown",
        "params": {},
        "sliderMax": 100,
        "sliderMin": 0,
        "spriteName": None,
        "value": 0,
        "visible": True,
        "width": 0,
        "x": 255,
        "y": 220,
    },
    { # [8]
        "height": 0,
        "id": "answer",
        "isDiscrete": True,
        "mode": "default",
        "opcode": "sensing_answer",
        "params": {},
        "sliderMax": 100,
        "sliderMin": 0,
        "spriteName": None,
        "value": 0,
        "visible": True,
        "width": 0,
        "x": 205,
        "y": 5,
    },
]

ALL_FR_MONITORS = [
    FRMonitor( # [0]
        id="5I9nI;7P)jdiR-_X;/%l_xposition",
        mode="default",
        opcode="motion_xposition",
        params={},
        sprite_name="Sprite1",
        value=0,
        x=5,
        y=5,
        visible=True,
        width=100,
        height=120,
        slider_min=0,
        slider_max=100,
        is_discrete=True,
    ),
    FRMonitor( # [1]
        id="5I9nI;7P)jdiR-_X;/%l_yposition",
        mode="default",
        opcode="motion_yposition",
        params={},
        sprite_name="Sprite1",
        value=0,
        x=5,
        y=31,
        visible=True,
        width=100,
        height=120,
        slider_min=0,
        slider_max=100,
        is_discrete=True,
    ),
    FRMonitor( # [2]
        id="$6=c?qlc|4Q*mK{XGC}z",
        mode="slider",
        opcode="data_variable",
        params={
            "VARIABLE": "globl",
        },
        sprite_name=None,
        value=0,
        x=110,
        y=76,
        visible=True,
        width=100,
        height=120,
        slider_min=-50.3,
        slider_max=100,
        is_discrete=False,
    ),
    FRMonitor( # [3]
        id="P4dp6h[X1|F3dYA4I?C`",
        mode="default",
        opcode="data_variable",
        params={
            "VARIABLE": "globl2",
        },
        sprite_name=None,
        value=0,
        x=216,
        y=128,
        visible=True,
        width=100,
        height=120,
        slider_min=-20,
        slider_max=100,
        is_discrete=True,
    ),
    FRMonitor( # [4]
        id="ru2NZobs(r+b[~|-rTCf",
        mode="list",
        opcode="data_listcontents",
        params={
            "LIST": "locl",
        },
        sprite_name="Sprite1",
        value=[],
        x=342,
        y=15,
        visible=True,
        width=100,
        height=198,
        slider_min=None,
        slider_max=None,
        is_discrete=None,
    ),
    FRMonitor( # [5]
        id="Zc!aC=9=36YS+pEb?kWj",
        mode="list",
        opcode="data_listcontents",
        params={
            "LIST": "globl",
        },
        sprite_name=None,
        value=[],
        x=36,
        y=153,
        visible=True,
        width=176,
        height=147,
        slider_min=None,
        slider_max=None,
        is_discrete=None,
    ),
    FRMonitor( # [6]
        id="8kv=.#:+,mIq:M5++hvu",
        mode="default",
        opcode="data_variable",
        params={
            "VARIABLE": "locl",
        },
        sprite_name="Sprite1",
        value=0,
        x=52,
        y=120,
        visible=True,
        width=100,
        height=120,
        slider_min=0,
        slider_max=100,
        is_discrete=True,
    ),
    FRMonitor( # [7]
        id="sensing_mousedown",
        mode="default",
        opcode="sensing_mousedown",
        params={},
        sprite_name=None,
        value=0,
        x=255,
        y=220,
        visible=True,
        width=100,
        height=120,
        slider_min=0,
        slider_max=100,
        is_discrete=True,
    ),
    FRMonitor( # [8]
        id="answer",
        mode="default",
        opcode="sensing_answer",
        params={},
        sprite_name=None,
        value=0,
        x=205,
        y=5,
        visible=True,
        width=100,
        height=120,
        slider_min=0,
        slider_max=100,
        is_discrete=True,
    ),
]


def test_FRMonitor_from_data():
    monitor_data = ALL_FR_MONITOR_DATAS[0]
    frmonitor = FRMonitor.from_data(monitor_data)
    assert isinstance(frmonitor, FRMonitor)
    assert frmonitor.id == monitor_data["id"]
    assert frmonitor.mode == monitor_data["mode"]
    assert frmonitor.opcode == monitor_data["opcode"]
    assert frmonitor.params == monitor_data["params"]
    assert frmonitor.sprite_name == monitor_data["spriteName"]
    assert frmonitor.value == monitor_data["value"]
    assert frmonitor.x == monitor_data["x"]
    assert frmonitor.y == monitor_data["y"]
    assert frmonitor.visible == monitor_data["visible"]
    assert frmonitor.width == monitor_data["width"]
    assert frmonitor.height == monitor_data["height"]
    assert frmonitor.slider_min == monitor_data["sliderMin"]
    assert frmonitor.slider_max == monitor_data["sliderMax"]
    assert frmonitor.is_discrete == monitor_data["isDiscrete"]

def test_FRMonitor_post_init():
    with raises(ThanksError):
        FRMonitor.from_data(ALL_FR_MONITOR_DATAS[1] | {"params": []})



