from pmp_manip.opcode_info.data_imports import *

class ExtensionDropdownType(DropdownType):
    colorParam = DropdownTypeInfo(
        direct_values=["color", "saturation", "brightness", "transparency"],
        rules=[],
        old_direct_values=["color", "saturation", "brightness", "transparency"],
        fallback=None,
    )
    layerParam = DropdownTypeInfo(
        direct_values=["front", "back"],
        rules=[],
        old_direct_values=["front", "back"],
        fallback=None,
    )
    italicsToggleParam = DropdownTypeInfo(
        direct_values=["on", "off"],
        rules=[],
        old_direct_values=["on", "off"],
        fallback=None,
    )
    FONT = DropdownTypeInfo(
        direct_values=[],
        rules=[
            DropdownValueRule.EXTENSION_UNPREDICTABLE,
        ],
        old_direct_values=[],
        fallback=None,
    )

class ExtensionInputType(InputType):
    colorParam = (InputMode.BLOCK_AND_DROPDOWN, None, ExtensionDropdownType.colorParam, 0)

extension = OpcodeInfoGroup(
    name="pen",
    opcode_info=DualKeyDict({
        ("pen_clear", "&pen::erase all"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_stamp", "&pen::stamp"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_penDown", "&pen::pen down"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_penUp", "&pen::pen up"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_setPenColorToColor", "&pen::set pen color to (COLOR)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("COLOR", "COLOR"): InputInfo(type=BuiltinInputType.COLOR, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_changePenColorParamBy", "&pen::change pen ([COLOR_PARAM]) by (VALUE)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("COLOR_PARAM", "COLOR_PARAM"): InputInfo(
                    type=ExtensionInputType.colorParam,
                    menu=MenuInfo(opcode="pen_menu_colorParam", inner="colorParam"),
                ),
                ("VALUE", "VALUE"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_setPenColorParamTo", "&pen::set pen ([COLOR_PARAM]) to (VALUE)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("COLOR_PARAM", "COLOR_PARAM"): InputInfo(
                    type=ExtensionInputType.colorParam,
                    menu=MenuInfo(opcode="pen_menu_colorParam", inner="colorParam"),
                ),
                ("VALUE", "VALUE"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_changePenSizeBy", "&pen::change pen size by (SIZE)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("SIZE", "SIZE"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_setPenSizeTo", "&pen::set pen size to (SIZE)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("SIZE", "SIZE"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_drawRect", "&pen::use (COLOR) to draw a square on x:[X] y:[Y] width:[WIDTH] height:[HEIGHT]"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("COLOR", "COLOR"): InputInfo(type=BuiltinInputType.COLOR, menu=None),
                ("X", "X"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("Y", "Y"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("WIDTH", "WIDTH"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("HEIGHT", "HEIGHT"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_drawArrayComplexShape", "&pen::draw polygon from points {:SHAPE:} with fill (COLOR)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("SHAPE", "SHAPE"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
                ("COLOR", "COLOR"): InputInfo(type=BuiltinInputType.COLOR, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_preloadUriImage", "&pen::preload image (URI) as (NAME)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("URI", "URI"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
                ("NAME", "NAME"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_unloadUriImage", "&pen::unload image (NAME)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("NAME", "NAME"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_drawUriImage", "&pen::draw image (URI) at x:[X] y:[Y]"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("URI", "URI"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
                ("X", "X"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("Y", "Y"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_drawUriImageWHR", "&pen::draw image (URI) at x:[X] y:[Y] width:[WIDTH] height:[HEIGHT] pointed at: (ROTATE)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("URI", "URI"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
                ("X", "X"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("Y", "Y"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("WIDTH", "WIDTH"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("HEIGHT", "HEIGHT"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("ROTATE", "ROTATE"): InputInfo(type=BuiltinInputType.DIRECTION, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_drawUriImageWHCX1Y1X2Y2R", "&pen::draw image (URI) at x:[X] y:[Y] width:[WIDTH] height:[HEIGHT] cropping from x:[CROPX] y:[CROPY] width:[CROPW] height:[CROPH] pointed at: (ROTATE)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("URI", "URI"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
                ("X", "X"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("Y", "Y"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("WIDTH", "WIDTH"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("HEIGHT", "HEIGHT"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("CROPX", "CROPX"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("CROPY", "CROPY"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("CROPW", "CROPW"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("CROPH", "CROPH"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("ROTATE", "ROTATE"): InputInfo(type=BuiltinInputType.DIRECTION, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_printText", "&pen::print (TEXT) on x:[X] y:[Y]"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("TEXT", "TEXT"): InputInfo(type=BuiltinInputType.TEXT, menu=None),
                ("X", "X"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
                ("Y", "Y"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_setPrintFont", "&pen::set print font to [FONT]"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict({
                ("FONT", "FONT"): DropdownInfo(type=ExtensionDropdownType.FONT),
            }),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_setPrintFontSize", "&pen::set print font size to (SIZE)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("SIZE", "SIZE"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_setPrintFontColor", "&pen::set print font color to (COLOR)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("COLOR", "COLOR"): InputInfo(type=BuiltinInputType.COLOR, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_setPrintFontStrokeColor", "&pen::set print stroke color to (COLOR)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("COLOR", "COLOR"): InputInfo(type=BuiltinInputType.COLOR, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_setPrintFontStrokeWidth", "&pen::set print stroke width to (WIDTH)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("WIDTH", "WIDTH"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_setPrintFontWeight", "&pen::set print font weight to (WEIGHT)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("WEIGHT", "WEIGHT"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_setPrintFontItalics", "&pen::turn print font italics [OPTION]"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict({
                ("OPTION", "OPTION"): DropdownInfo(type=ExtensionDropdownType.italicsToggleParam),
            }),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_drawComplexShape", "&pen::draw triangle {:SHAPE:} with fill (COLOR)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("SHAPE", "SHAPE"): InputInfo(type=BuiltinInputType.POLYGON, menu=None),
                ("COLOR", "COLOR"): InputInfo(type=BuiltinInputType.COLOR, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_draw4SidedComplexShape", "&pen::draw quadrilateral {:SHAPE:} with fill (COLOR)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("SHAPE", "SHAPE"): InputInfo(type=BuiltinInputType.POLYGON, menu=None),
                ("COLOR", "COLOR"): InputInfo(type=BuiltinInputType.COLOR, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_setPenShadeToNumber", "&pen::LEGACY - set pen shade to (SHADE)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("SHADE", "SHADE"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_changePenShadeBy", "&pen::LEGACY - change pen shade by (SHADE)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("SHADE", "SHADE"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_setPenHueToNumber", "&pen::LEGACY - set pen color to (HUE)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("HUE", "HUE"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_changePenHueBy", "&pen::LEGACY - change pen color by (HUE)"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict({
                ("HUE", "HUE"): InputInfo(type=BuiltinInputType.NUMBER, menu=None),
            }),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_goPenLayer", "&pen::go to [OPTION] layer"): OpcodeInfo(
            opcode_type=OpcodeType.STATEMENT,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict({
                ("OPTION", "OPTION"): DropdownInfo(type=ExtensionDropdownType.layerParam),
            }),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=False,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_menu_colorParam", "pen_menu_colorParam"): OpcodeInfo(
            opcode_type=OpcodeType.MENU,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=True,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_menu_layerParam", "pen_menu_layerParam"): OpcodeInfo(
            opcode_type=OpcodeType.MENU,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=True,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_menu_italicsToggleParam", "pen_menu_italicsToggleParam"): OpcodeInfo(
            opcode_type=OpcodeType.MENU,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=True,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
        ("pen_menu_FONT", "pen_menu_FONT"): OpcodeInfo(
            opcode_type=OpcodeType.MENU,
            inputs=DualKeyDict(),
            dropdowns=DualKeyDict(),
            can_have_monitor=False,
            monitor_id_behaviour=None,
            has_shadow=True,
            has_variable_id=False,
            special_cases={},
            old_mutation_cls=None,
            new_mutation_cls=None,
        ),
    }),
)