# Events (Complete)
opcodes = {
    "event_whenflagclicked": {
        "type": "hat",
        "category": "Events",
        "newOpcode": "when green flag clicked",
        "inputTypes": {},
        "optionTypes": {},
    },
    "event_whenstopclicked": {
        "type": "hat",
        "category": "Events",
        "newOpcode": "when stop clicked",
        "inputTypes": {},
        "optionTypes": {},
    },
    "event_always": {
        "type": "hat",
        "category": "Events",
        "newOpcode": "always",
        "inputTypes": {},
        "optionTypes": {},
    },
    "event_whenanything": {
        "type": "hat",
        "category": "Events",
        "newOpcode": "when <CONDITION>",
        "inputTypes": {"CONDITION": "boolean"},
        "inputTranslation": {"ANYTHING": "CONDITION"},
        "optionTypes": {},
    },
    "event_whenkeypressed": {
        "type": "hat",
        "category": "Events",
        "newOpcode": "when [KEY] key pressed",
        "inputTypes": {},
        "optionTypes": {"KEY": "key"},
        "optionTranslation": {"KEY_OPTION": "KEY"},
    },
    "event_whenkeyhit": {
        "type": "hat",
        "category": "Events",
        "newOpcode": "when [KEY] key hit",
        "inputTypes": {},
        "optionTypes": {"KEY": "key"},
        "optionTranslation": {"KEY_OPTION": "KEY"},
    },
    "event_whenmousescrolled": {
        "type": "hat",
        "category": "Events",
        "newOpcode": "when mouse is scrolled [DIRECTION]",
        "inputTypes": {},
        "optionTypes": {"DIRECTION": "up|down"},
        "optionTranslation": {"KEY_OPTION": "DIRECTION"},
    },
    "event_whenthisspriteclicked": { # for sprites
        "type": "hat",
        "category": "Events",
        "newOpcode": "when this sprite clicked",
        "inputTypes": {},
        "optionTypes": {},
    },
    "event_whenstageclicked": { # for the stage
        "type": "hat",
        "category": "Events",
        "newOpcode": "when stage clicked",
        "inputTypes": {},
        "optionTypes": {},
    },
    "event_whenbackdropswitchesto": {
        "type": "hat",
        "category": "Events",
        "newOpcode": "when backdrop switches to [BACKDROP]",
        "inputTypes": {},
        "optionTypes": {"BACKDROP": "backdrop"},
    },
    "event_whengreaterthan": {
        "type": "hat",
        "category": "Events",
        "newOpcode": "when [OPTION] > (VALUE)",
        "inputTypes": {"VALUE": "number"},
        "optionTypes": {"OPTION": "loudness|timer"},
        "optionTranslation": {"WHENGREATERTHANMENU": "OPTION"},
    },
    "event_whenbroadcastreceived": {
        "type": "hat",
        "category": "Events",
        "newOpcode": "when I receive [MESSAGE]",
        "inputTypes": {},
        "optionTypes": {"MESSAGE": "broadcast"},
        "optionTranslation": {"BROADCAST_OPTION": "MESSAGE"},
    },
    "event_broadcast": {
        "type": "instruction",
        "category": "Events",
        "newOpcode": "broadcast ([MESSAGE])",
        "inputTypes": {"MESSAGE": "broadcast"},
        "inputTranslation": {"BROADCAST_INPUT": "MESSAGE"},
        "optionTypes": {},
    },
    "event_broadcastandwait": {
        "type": "instruction",
        "category": "Events",
        "newOpcode": "broadcast ([MESSAGE]) and wait",
        "inputTypes": {"MESSAGE": "broadcast"},
        "inputTranslation": {"BROADCAST_INPUT": "MESSAGE"},
        "optionTypes": {},
    },
}