opcodes = {
    "pen_clear": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "erase all",
        "inputTypes": {},
        "optionTypes": {},
    },
    "pen_stamp": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "stamp",
        "inputTypes": {},
        "optionTypes": {},
    },
    "pen_setPrintFont": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set print font to ([FONT])",
        "inputTypes": {"FONT": "font"},
        "optionTypes": {},
        "menus": [{"new": "FONT", "outer": "FONT", "inner": "FONT", "menuOpcode": "pen_menu_FONT"}],
    },
    "pen_setPrintFontSize": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set print font size to (SIZE)",
        "inputTypes": {"SIZE": "number"},
        "optionTypes": {},
    },
    "pen_setPrintFontColor": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set print font color to (COLOR)",
        "inputTypes": {"COLOR": "color"},
        "optionTypes": {},
    },
    "pen_setPrintFontWeight": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set print font wheight to (WEIGHT)",
        "inputTypes": {"WEIGHT": "number"},
        "optionTypes": {},
    },
    "pen_setPrintFontItalics": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set print font italics to [ON_OFF]",
        "inputTypes": {},
        "optionTypes": {"ON_OFF": "on|off"},
        "optionTranslation": {"OPTION": "ON_OFF"},
    },
    "pen_printText": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "print (TEXT) on x: (X) y: (Y)",
        "inputTypes": {"TEXT": "text", "X": "number", "Y": "number"},
        "optionTypes": {},
    },
    "pen_preloadUriImage": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "preload image (URI) as (NAME)",
        "inputTypes": {"URI": "text", "NAME": "text"},
        "optionTypes": {},
    },
    "pen_unloadUriImage": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "unload image (NAME)",
        "inputTypes": {"NAME": "text"},
        "optionTypes": {},
    },
    "pen_drawUriImage": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "draw image (URI) at x: (X) y: (Y)",
        "inputTypes": {"URI": "text", "X": "number", "Y": "number"},
        "optionTypes": {},
    },
    "pen_drawUriImageWHR":  {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "draw image (URI) at x: (X) y: (Y) width: (WIDTH) height: (HEIGHT) pointed at: (ROTATE)",
        "inputTypes": {"URI": "text", "X": "number", "Y": "number", "WIDTH": "number", "HEIGHT": "number", "ROTATE": "number"},
        "optionTypes": {},
    },
    "pen_drawUriImageWHCX1Y1X2Y2R":  {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "draw image (URI) at x: (X) y: (Y) width: (WIDTH) height: (HEIGHT) cropping from x: (CROPX) y: (CROPY) width: (CROPWIDTH) height: (CROPHEIGHT) pointed at: (ROTATE)",
        "inputTypes": {"URI": "text", "X": "number", "Y": "number", "WIDTH": "number", "HEIGHT": "number", "CROPX": "number", "CROPY": "number", "CROPWIDTH": "number", "CROPHEIGHT": "number", "ROTATE": "number"},
        "inputTranslation": {"CROPW": "CROPWIDTH", "CROPH": "CROPHEIGHT"},
        "optionTypes": {},
    },
    "pen_drawRect": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "use (COLOR) to draw a square on x: (X) y: (Y) width: (WIDTH) height: (HEIGHT)",
        "inputTypes": {"COLOR": "color", "X": "number", "Y": "number", "WIDTH": "number", "HEIGHT": "number"},
        "optionTypes": {},
    },
    "pen_drawComplexShape": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "draw triangle (TRIANGLE) with fill (COLOR)",
        "inputTypes": {"TRIANGLE": "embeddedMenu", "COLOR": "color"},
        "inputTranslation": {"SHAPE": "TRIANGLE"},
        "optionTypes": {},
        "embeddedMenuOpcode": "polygon",
    },
    "pen_draw4SidedComplexShape": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "draw quadrilateral (QUADRILATERAL) with fill (COLOR)",
        "inputTypes": {"QUADRILATERAL": "embeddedMenu", "COLOR": "color"},
        "inputTranslation": {"SHAPE": "QUADRILATERAL"},
        "optionTypes": {},
        "embeddedMenuOpcode": "polygon",
    },
    "pen_drawArrayComplexShape": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "draw polygon from points (POINTS) with fill (COLOR)",
        "inputTypes": {"POINTS": "text", "COLOR": "color"},
        "inputTranslation": {"SHAPE": "POINTS"},
        "optionTypes": {},
    },
    "pen_penDown": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "pen down",
        "inputTypes": {},
        "optionTypes": {},
    },
    "pen_penUp": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "pen up",
        "inputTypes": {},
        "optionTypes": {},
    },
    "pen_setPenColorToColor": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set pen color to (COLOR)",
        "inputTypes": {"COLOR": "color"},
        "optionTypes": {},
    },
    "pen_changePenColorParamBy": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "change pen ([PROPERTY]) by (VALUE)",
        "inputTypes": {"PROPERTY": "pen property", "VALUE": "text"},
        "optionTypes": {},
        "menus": [{"new": "PROPERTY", "outer": "COLOR_PARAM", "inner": "colorParam", "menuOpcode": "pen_menu_colorParam"}],
    },
    "pen_setPenColorParamTo": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set pen ([PROPERTY]) to (VALUE)",
        "inputTypes": {"PROPERTY": "pen property", "VALUE": "text"},
        "optionTypes": {},
        "menus": [{"new": "PROPERTY", "outer": "COLOR_PARAM", "inner": "colorParam", "menuOpcode": "pen_menu_colorParam"}],
    },
    "pen_changePenSizeBy": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "change pen size by (SIZE)",
        "inputTypes": {"SIZE": "text"},
        "optionTypes": {},
    },
    "pen_setPenSizeTo": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "set pen size to (SIZE)",
        "inputTypes": {"SIZE": "text"},
        "optionTypes": {},
    },
    "pen_setPenShadeToNumber": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "LEGACY - set pen shade to (SHADE)",
        "inputTypes": {"SHADE": "number"},
        "optionTypes": {},
    },
    "pen_changePenShadeBy": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "LEGACY - change pen shade by (SHADE)",
        "inputTypes": {"SHADE": "number"},
        "optionTypes": {},
    },
    "pen_setPenHueToNumber": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "LEGACY - set pen color to (HUE)",
        "inputTypes": {"HUE": "number"},
        "optionTypes": {},
    },
    "pen_changePenHueBy": {
        "type": "instruction",
        "category": "Pen",
        "newOpcode": "LEGACY - change pen color by (HUE)",
        "inputTypes": {"HUE": "number"},
        "optionTypes": {},
    },
}